--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/platz1de/EasyEdit
build-by-default: true
projects:
  EasyEdit:
    path: ""
    lint:
      phpstan: false
      syntaxError: false
...
