name: EasyEdit
main: platz1de\EasyEdit\EasyEdit
api: 3.0.0
version: 1.0.0
author: platz1de
permissions:
 easyedit:
  default: op
  children:
   easyedit.command:
    default: op
    children:
     easyedit.command.set:
      default: op
     easyedit.command.undo:
      default: op
     easyedit.command.redo:
      default: op
     easyedit.command.copy:
      default: op
     easyedit.command.paste:
      default: op
     easyedit.command.brush:
      default: op
   easyedit.position:
    default: op
   easyedit.brush:
    default: op