name: EasyEdit
main: platz1de\EasyEdit\EasyEdit
api: 3.0.0
version: 0.0.1
author: platz1de
permissions:
 easyedit:
  default: op
  children:
   easyedit.command:
    default: op
    children:
     easyedit.command.set:
      default: op
   easyedit.position:
    default: op