name: EasyEdit
main: platz1de\EasyEdit\EasyEdit
api: 4.0.0
version: 1.2.0-dev
author: platz1de
permissions:
 easyedit.command.set:
  default: op
 easyedit.command.undo:
  default: op
 easyedit.command.redo:
  default: op
 easyedit.command.copy:
  default: op
 easyedit.command.paste:
  default: op
 easyedit.command.brush:
  default: op
 easyedit.command.count:
  default: op
 easyedit.command.thread:
  default: op
 easyedit.command.info:
  default: op
 easyedit.command.loadschematic:
  default: op
 easyedit.position:
  default: op
 easyedit.brush:
  default: op