config-version: "1.2.6" #Please don't change this manually

#Whether to allow user with "easyedit.history.other" permission to undo/redo other people's actions
allow-history-other: true

#Blocks which get ignored when calculating terrain height (e.g. when smoothing) or inserting selection
#These get replaced with air when edited
terrain-ignored-blocks: [ "air", "wood", "wood2", "leaves", "leaves2", "dandelion", "poppy", "tall_grass", "water", "8", "lava", "10", "snow_layer", "carpet" ]



#Better don't change this, the following is mainly for transparency
#Conversion data source, requires specific Format
#for more information see https://github.com/platz1de/EasyEdit-Data
bedrock-convert-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/master/bedrock-conversion-map.json"
bedrock-palette-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/master/bedrock_palette.json"
java-palette-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/master/java_palette.json"
rotation-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/master/rotation-data.json"