config-version: "1.2.8" #Please don't change this manually

#Whether to allow user with "easyedit.history.other" permission to undo/redo other people's actions
allow-history-other: true

#Blocks which get ignored when calculating terrain height (e.g. when smoothing) or inserting selection
#These get replaced with air when edited
terrain-ignored-blocks: [ "air", "wood", "wood2", "leaves", "leaves2", "dandelion", "poppy", "tall_grass", "water", "8", "lava", "10", "snow_layer", "carpet" ]

#Whether to send spammy debug messages into the console
#requires server to be on debug mode
send-debug: false


#Better don't change this, the following is mainly for transparency
#Conversion data source, requires specific Format
#for more information see https://github.com/platz1de/EasyEdit-Data/tree/format-v2.0
#If you want to use your own data, the simplest way is to fork the data repository and modify some values
bedrock-convert-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/bedrock-conversion-map.json"
bedrock-palette-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/bedrock_palette.json"
java-palette-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/java_palette.json"
rotation-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/rotation-data.json"
flip-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/flip-data.json"