config-version: "1.2.1" #Please don't change this manually

#Blocks which get ignored when calculating height (e.g. when smoothing)
#These get replaced with air when edited
height-ignored-blocks: [ "air", "wood", "wood2", "leaves", "leaves2", "dandelion", "poppy", "tall_grass", "water", "lava", "snow_layer", "carpet" ]